query BookReview($slug: String!) {  
  bookReviews(where: { slug: $slug }) {
    id
    title
    content
    opinion
    rating
    manually_published_at
    book_published_date
    slug
    topics
    authors {
      id
      public
      first_name
      last_name
      description
      slug
      avatar {
        id
        url
      }
    }
    quotes {
      id
      excerpt
      content
      description
      date
      public
      book_order
      location
    }
    cover {
      id
      url
    }
    images {
      id
      url
    }
    comment_thread {
      id
    }
  }
}