query BookReviews {
  bookReviews(where: { public: true }) {
    id
    title
    description
    rating
    manually_published_at
    book_published_date
    slug
    topics
    authors {
      id
      first_name
      last_name
      public
      description
      slug
      avatar {
        id
        url
      }
    }
    cover {
      id
      url
    }
  }
}
