query Timeline($slug: String!) {
  timelines(where: { slug: $slug }) {
    id
    slug
    title
    description
    image {
      id
      formats
      url
    }
    timeline_entries {
      id
      title
      description
      year
      month
      date
      images {
        id
        formats
        url
      }
      tags {
        id
        title
        color
        icon {
          id
          formats
          url
        }
        icon_class
      }
      blog_posts {
        id
        slug
        title
        description
        tagline
        image_header {
          id
          url
          formats
        }
      }
      links {
        id
        title
        url
        key
        target
      }
    }
  }
}
