query CommentThread($id: ID!) {  
  commentThread(id: $id) {
    id
    comments {
      id
      text
      hidden
      created_at
      hidden
      hidden_reason
      user {
        id
        username
        firstName
        lastName
        blocked
        image {
          id
          url
        }
      }
      comment_thread {
        id
      }
    }
  }
}