mutation CreateCommentThread($commentThreadInput: CommentThreadInput!) {
    createCommentThread(
      input: { data: $commentThreadInput },
    ) {
      commentThread {
        id
      }
    }
  }