mutation UpdateCommentThread($commentThreadInput: editCommentThreadInput!, $threadId: ID!) {
    updateCommentThread(
      input: { 
        data: $commentThreadInput,
        where: { id: $threadId } 
      }
    ) {
      commentThread {
        id
      }
    }
  }