query HomePageSettings {
  homePageSetting {
    featured_blog_series {
      id
      title
      slug
      show_star_svg
      description
      image_header {
        id
        url
        formats
      }
    }
  }
}
