defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[acme]
[[acme.domains]]
  main = "perspectiveswithjosh.com"
  sans = ["monitor.perspectiveswithjosh.com", "api.perspectiveswithjosh.com", "apiv2.perspectiveswithjosh.com", "www.perspectiveswithjosh.com"]
[[acme.domains]]
  main = "joshoncode.com"
  sans = ["monitor.joshoncode.com", "api.joshoncode.com", "apiv2.joshoncode.com", "www.joshoncode.com"]