query BlogPostSeries($id: ID!) {
  blogSery(id: $id) {
    id
    slug
    title
    description
    manually_published_at
    background_color
    authors {
      id
      username
    }
    image_header {
      id
      url
    }
    blog_post_categories {
      id
      name
    }
    blog_posts {
      id
      title
      slug
      show_description
      description
      manually_published_at
      background_color
      foreground_color
      use_default_post_background
      blog_series_order
      public
      image_header {
        id
        url
      }
      show_in_series_only
      blog_series {
        id
        title
        blog_posts {
          id
        }
      }
    }
  }
}
