query BlogPosts($slug: String!) {  
  blogPosts(where: { slug: $slug }) {
    id
    slug
    title
    description
    content
    manually_published_at
    show_in_series_only
    use_default_post_background
    background_color
    foreground_color
    show_description
    blog_series_order
    image_header {
      id
      url
    }
    blog_series {
      id
      title
      slug
      blog_posts {
        id
      }
    }
    links {
      id
      title
      description
      url
      target
      icon {
        url
      }
    }
    comment_thread {
      id
    }
  }
}