query Category($id: ID!){
  blogPostCategory(id: $id) {
    id
    name
    description
    blog_posts {
      id
      slug
      title
      manually_published_at
      background_color
      foreground_color
      description
      blog_series_order
      use_default_post_background
      show_description
      image_header {
        id
        url
      }
      blog_series {
        id
        slug
        title
        blog_posts {
          id
        }
      }
    }
  }
}